# Generated by Django 5.1 on 2024-10-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
