# Generated by Django 5.0.8 on 2024-10-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_category_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="low_stock_threshold",
            field=models.IntegerField(default=10),
        ),
    ]
